THD/Controllers/MyRoomController.cs
using AutoMapper;

using THD.Service.Dtos;
using THD.Service.Interfaces;
using THD.Web.Controllers.Abstract;
using THD.Web.Models.Food;
using THD.Web.Models.User;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

using Volo.Abp;

namespace THD.Web.Controllers
{
    public class MyRoomController : MvcControllerBase<MyRoomController>
    {
        private readonly IWebHostEnvironment _environment;
        private readonly IUserAppService _userAppService;

        public MyRoomController(
            ILogger<MyRoomController> logger,
            IMapper mapper,
            IWebHostEnvironment environment,
            IUserAppService userAppService)
            : base(logger, mapper)
        {
            _environment = environment;
            _userAppService = userAppService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> MemberInfo()
        {
            var userDto = await _userAppService.GetAsync(int.Parse(UserId));
            var userView = Mapper.Map<UserViewModel>(userDto);
            return View(userView);
        }

        [HttpPost]
        public async Task<IActionResult> MemberInfo([FromForm] UserViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }
            var userDto = await _userAppService.GetAsync(input.Id);
            if (userDto is null) throw new UserFriendlyException("找不到用户");
            userDto.Name = input.Name;
            userDto.Type = input.Type;
            userDto.Email = input.Email;
            userDto.Address = input.Address;
            userDto.QQ = input.QQ;
            userDto.WeChat = input.WeChat;
            userDto.GSMC = input.GSMC;
            userDto.GSDH = input.GSDH;
            userDto.GSYX = input.GSYX;
            userDto.GSCZ = input.GSCZ;
            userDto.GSDZ = input.GSDZ;
            var user = await _userAppService.EditAsync(userDto);
            var userView = Mapper.Map<UserViewModel>(user);
            return View(userView);
        }

        public async Task<IActionResult> Photo()
        {
            var userDto = await _userAppService.GetAsync(int.Parse(UserId));
            ViewBag.Id = userDto.Id;
            ViewBag.Pic = userDto.Pic;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Photo(int id, IFormFile fileImg)
        {
            var userDto = await _userAppService.GetAsync(id);
            if (userDto is null) throw new UserFriendlyException("找不到用户");
            if (fileImg is not null)
            {
                userDto.Pic = await GetFilePath(fileImg, "User", "Img" + id);
                userDto = await _userAppService.EditAsync(userDto);
            }
            ViewBag.Id = userDto.Id;
            ViewBag.Pic = userDto.Pic;
            return View();
        }

        public IActionResult PasswordChange()
        {
            return View(new UserPwdViewModel { Id = int.Parse(UserId) });
        }

        [HttpPost]
        public async Task<IActionResult> PasswordChange(UserPwdViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }
            if (input.NewPassword != input.ConfirmePassword)
            {
                ModelState.AddModelError("ConfirmePassword", "输入密码不一致");
                return View(input);
            }
            var userDto = await _userAppService.GetAsync(input.Id);
            if (userDto is null) throw new UserFriendlyException("找不到用户");

            if (userDto.Password != input.OldPassword)
            {
                ModelState.AddModelError("OldPassword", "密码错误");
                return View(input);
            }

            userDto.Password = input.NewPassword;
            userDto = await _userAppService.EditAsync(userDto);
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Login", "Account");
        }

        public IActionResult Quitters()
        {
            ViewBag.Id = UserId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Quitters(int id)
        {
            var userDto = await _userAppService.GetAsync(id);
            if (userDto is null) throw new UserFriendlyException("找不到用户");
            userDto.IsDelete = true;
            await _userAppService.EditAsync(userDto);
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return new EmptyResult();
        }

        private async Task<string> GetFilePath(IFormFile file, string folderName, string symbol = "")
        {
            if (file is null) return "";
            var fileName = folderName + symbol + "_" + DateTime.Now.ToString("yyyyMMddhhmmssfff") + Path.GetExtension(file.FileName);
            var uploadsRootFolder = Path.Combine(_environment.WebRootPath, "uploadfile", folderName);
            if (!Directory.Exists(uploadsRootFolder))
            {
                Directory.CreateDirectory(uploadsRootFolder);
            }
            var savePath = Path.Combine(uploadsRootFolder, fileName);
            using (var fileStream = new FileStream(savePath, FileMode.Create))
            {
                await file.CopyToAsync(fileStream);
            }
            return savePath.Replace(_environment.WebRootPath, "").Replace("\\", "/");
        }
    }
}

THD/Controllers/SystemController.cs
using AutoMapper;

using THD.Service.Dtos;
using THD.Service.Dtos.Users;
using THD.Service.Interfaces;
using THD.Web.Controllers.Abstract;
using THD.Web.Core.Options;
using THD.Web.Models.Food;
using THD.Web.Models.Guide;
using THD.Web.Models.Pickup;
using THD.Web.Models.Play;
using THD.Web.Models.Stay;
using THD.Web.Models.Ticket;
using THD.Web.Models.Tour;
using THD.Web.Models.User;

using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace THD.Web.Controllers
{
    public class SystemController : MvcControllerBase<SystemController>
    {
        private readonly IWebHostEnvironment _environment;
        private readonly ITourAppService _tourAppService;
        private readonly IStayAppService _stayAppService;
        private readonly ITicketAppService _ticketAppService;
        private readonly IFoodAppService _foodAppService;
        private readonly IPickupAppService _pickupAppService;
        private readonly IGuideAppService _guideAppService;
        private readonly IPlayAppService _playAppService;
        private readonly IUserAppService _userAppService;
        private readonly ITechnicianAppService _technicianAppService;
        private readonly IItListInfoAppService _itListInfoAppService;
        private readonly ICorporateAppService _corporateAppService;

        public SystemController(
            ILogger<SystemController> logger,
            IMapper mapper,
            IWebHostEnvironment environment,
            ITourAppService tourAppService,
            IStayAppService stayAppService,
            ITicketAppService ticketAppService,
            IFoodAppService foodAppService,
            IPickupAppService pickupAppService,
            IGuideAppService guideAppService,
            IPlayAppService playAppService,
            IUserAppService userAppService,
            ITechnicianAppService technicianAppService,
            IItListInfoAppService itListInfoAppService,
            ICorporateAppService corporateAppService)
            : base(logger, mapper)
        {
            _environment = environment;
            _tourAppService = tourAppService;
            _stayAppService = stayAppService;
            _ticketAppService = ticketAppService;
            _foodAppService = foodAppService;
            _pickupAppService = pickupAppService;
            _guideAppService = guideAppService;
            _playAppService = playAppService;
            _userAppService = userAppService;
            _technicianAppService = technicianAppService;
            _itListInfoAppService = itListInfoAppService;
            _corporateAppService = corporateAppService;
        }

        public IActionResult Index()
        {
            return View();
        }

        #region 案件发布

        public IActionResult AddItListInfo(int? id)
        {
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public async Task<ItListInfoDto> GetItListInfo([FromBody] int id)
        {
            return await _itListInfoAppService.GetAsync(id);
        }

        [HttpPost]
        public async Task<bool> AddItListInfo([FromBody] ItListInfoDto input)
        {
            input.user = this.UserId;
            input.update = DateTime.Now.ToString();
            var id = await _itListInfoAppService.AddOrEditAsync(input);
            if (id <= 0) throw new Exception("案件发布失败");
            return true;
        }

        public IActionResult ItListInfoList()
        {
            return View();
        }

        [HttpPost]
        public async Task<PagedResultDto<ItListInfoDto>> GetItListInfoList([FromBody] ItListInfoPagedQueryDto input)
        {
            var dtos = await _itListInfoAppService.GetListAsync(input);
            return dtos;
        }

        [HttpPost]
        public async Task<bool> DeleteItListInfo([FromBody] int id)
        {
            return await _itListInfoAppService.DeleteAsync(id);
        }

        #endregion

        #region 住宿发布

        public async Task<IActionResult> AddStay(int? id)
        {
            if (id.HasValue && id.Value > 0)
            {
                var stay = await _stayAppService.GetAsync(id.Value);
                var stayView = Mapper.Map<StayViewModel>(stay);
                return View(stayView);
            }
            return View(new StayViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> AddStay([FromForm] StayViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }
            var stayDto = Mapper.Map<StayDto>(input);
            if (input.FileImg1 is not null)
                stayDto.Img1 = await GetFilePath(input.FileImg1, "Stay", "Img1");
            if (input.FileImg2 is not null)
                stayDto.Img2 = await GetFilePath(input.FileImg2, "Stay", "Img2");
            if (input.FileImg3 is not null)
                stayDto.Img3 = await GetFilePath(input.FileImg3, "Stay", "Img3");
            if (input.FileImg4 is not null)
                stayDto.Img4 = await GetFilePath(input.FileImg4, "Stay", "Img4");
            if (input.FileImg5 is not null)
                stayDto.Img5 = await GetFilePath(input.FileImg5, "Stay", "Img5");
            if (input.FileImg6 is not null)
                stayDto.Img6 = await GetFilePath(input.FileImg6, "Stay", "Img6");
            if (input.FileImg7 is not null)
                stayDto.Img7 = await GetFilePath(input.FileImg7, "Stay", "Img7");
            if (input.FileImg8 is not null)
                stayDto.Img8 = await GetFilePath(input.FileImg8, "Stay", "Img8");
            if (input.FileImg9 is not null)
                stayDto.Img9 = await GetFilePath(input.FileImg9, "Stay", "Img9");
            if (input.FileImg10 is not null)
                stayDto.Img10 = await GetFilePath(input.FileImg10, "Stay", "Img10");

            var id = await _stayAppService.AddOrEditAsync(stayDto);
            if (id <= 0) throw new Exception("住宿发布失败");

            return Redirect("/Stay/Index");
        }

        public IActionResult StayList()
        {
            return View();
        }

        [HttpPost]
        public async Task<bool> DeleteStay([FromBody] int id)
        {
            return await _stayAppService.DeleteAsync(id);
        }

        #endregion

        #region 票券发布

        public async Task<IActionResult> AddTicket(int? id)
        {
            if (id.HasValue && id.Value > 0)
            {
                var ticket = await _ticketAppService.GetAsync(id.Value);
                var ticketView = Mapper.Map<TicketViewModel>(ticket);
                return View(ticketView);
            }
            return View(new TicketViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> AddTicket([FromForm] TicketViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }
            var ticketDto = Mapper.Map<TicketDto>(input);
            if (input.FileImg1 is not null)
                ticketDto.Img1 = await GetFilePath(input.FileImg1, "Ticket", "Img1");
            if (input.FileImg2 is not null)
                ticketDto.Img2 = await GetFilePath(input.FileImg2, "Ticket", "Img2");
            if (input.FileImg3 is not null)
                ticketDto.Img3 = await GetFilePath(input.FileImg3, "Ticket", "Img3");
            if (input.FileImg4 is not null)
                ticketDto.Img4 = await GetFilePath(input.FileImg4, "Ticket", "Img4");
            if (input.FileImg5 is not null)
                ticketDto.Img5 = await GetFilePath(input.FileImg5, "Ticket", "Img5");
            if (input.FileImg6 is not null)
                ticketDto.Img6 = await GetFilePath(input.FileImg6, "Ticket", "Img6");
            if (input.FileImg7 is not null)
                ticketDto.Img7 = await GetFilePath(input.FileImg7, "Ticket", "Img7");
            if (input.FileImg8 is not null)
                ticketDto.Img8 = await GetFilePath(input.FileImg8, "Ticket", "Img8");
            if (input.FileImg9 is not null)
                ticketDto.Img9 = await GetFilePath(input.FileImg9, "Ticket", "Img9");
            if (input.FileImg10 is not null)
                ticketDto.Img10 = await GetFilePath(input.FileImg10, "Ticket", "Img10");

            var id = await _ticketAppService.AddOrEditAsync(ticketDto);
            if (id <= 0) throw new Exception("票券发布失败");

            return Redirect("/Ticket/Index");
        }

        public IActionResult TicketList()
        {
            return View();
        }

        [HttpPost]
        public async Task<bool> DeleteTicket([FromBody] int id)
        {
            return await _ticketAppService.DeleteAsync(id);
        }

        #endregion

        #region 美食发布

        public async Task<IActionResult> AddFood(int? id)
        {
            if (id.HasValue && id.Value > 0)
            {
                var food = await _foodAppService.GetAsync(id.Value);
                var foodView = Mapper.Map<FoodViewModel>(food);
                return View(foodView);
            }
            return View(new FoodViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> AddFood([FromForm] FoodViewModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }
            var foodDto = Mapper.Map<FoodDto>(input);
            if (input.FileImg1 is not null)
                foodDto.Img1 = await GetFilePath(input.FileImg1, "Food", "Img1");
            if (input.FileImg2 is not null)
                foodDto.Img2 = await GetFilePath(input.FileImg2, "Food", "Img2");
            if (input.FileImg3 is not null)
                foodDto.Img3 = await GetFilePath(input.FileImg3, "Food", "Img3");

THD/Views/Shared/_Footer.cshtml
@*<div class="footer-wrapper">
    <div class="content-inner">
        <div class="footer-nav">
            <div class="footer-box">
                <div class="footer-item">
                    <div class="footer-item-title">
                        <a href="#">方針規約</a>
                    </div>
                    <div class="footer-item-li">
                        <a href="#">個人情報保護方針</a>
                    </div>
                    <div class="footer-item-list">
                        <div class="footer-item-li">
                            <a href="#">個人情報の取り扱いについて</a>
                        </div>
                        <div class="footer-item-li">
                            <a href="#">情報セキュリティ基本方針</a>
                        </div>
                        <div class="footer-item-li">
                            <a href="#">人材派遣サービス利用規約</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-link">
            <a href="#">個人情報保護方針</a>
            <a href="#">個人情報の取り扱いについて</a>
            <a href="#">情報セキュリティ基本方針</a>
            <a href="#">人材派遣サービス利用規約</a>
        </div>
        <div class="footer-link">
            <a href="#">サイトのご利用にあたって</a>
            <a href="#">労働者派遣法に基づく派遣事業の情報</a>
            <a href="#"></a>
            <a href="#"></a>
        </div>
        <div class="footer-link">
            <a href="#">お問い合わせ</a>
            <a href="#">よくあるご質問</a>
            <a href="#">サイトマップ</a>
            <a href="#"></a>
        </div>
    </div>
</div>*@

<div class="logo-copyright">
    <div class="logo-slogan">
        <a href="/Link/Disclosure/">個人情報保護方針</a>
        <a href="/Link/Index/">個人情報の取り扱いについて</a>
        <a href="/Link/Policy/">情報セキュリティ基本方針</a>
        <a href="/Link/Info/">人材派遣サービス利用規約</a>
        <a href="/Corporate/contact/">お問い合わせ</a>
        <a href="/Link/Woman/">よくあるご質問</a>
        <a href="/Link/Terms/">サイトマップ</a>
    </div>
    <div class="copyright">&copy; THD CO.,LTD</div>
</div>

THD/Views/Shared/_Header.cshtml
@{
    string type = string.Empty;
    if (User.Identity.IsAuthenticated)
        type = User.Claims?.FirstOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.Role).Value;
}
<style type="text/css">
    .googleAPI {
        background-color:red;
        border:none;
    }
</style>
<div class="header">
    <div class="header-wrapper font-weight-bold">
            <a class="header-logo" href="/">
                <p><img src="/img/logo/logo1.jpg" alt="株式会社登峰開発" width="60"></p>
                <div style="font-size: 26px; font-weight: bold; color: #3c3c3c; display: block;margin-left:3px;">
                    株式会社登峰開発
                    <span style="font-size: 15px; display: block; color: #3c3c3c; margin-top: -6px;">www.tohodevlop.co.jp</span>
                </div>
            </a>
            <div class="header-list">
                <a href="/Dispatch/">人材派遣</a>
                <a href="/Sale/">製品販売</a>
                <a href="/Soft/">ソフト開発</a>
                <a href="/Technology/">先進技術応援</a>
            </div>
            @*<div class="header-consult">
                <a href="/contact/">お問い合わせ</a>
            </div>*@
            @* google 翻译标签 *@
            @*<div id="google_translate_element"></div>
            <div class="header-btn googleAPI" id="headerBtn">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            </div>*@
    </div>
    <div class="header-list-phone">
        <a href="/worker/">仕事を見つける</a>
        <a href="#">会社の代表者</a>
        <a href="/company/">私たちに関しては</a>
        <a href="/recruit/">雇用情報</a>
        <a href="/company/branch/">拠点一覧</a>
    </div>
</div>

THD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <!-- elemnt-plus -->
    <link rel="stylesheet" href="~/lib/element-plus/dist/index.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/common.css" />
    <link rel="stylesheet" href="~/css/index.css" />
    <link rel="stylesheet" href="~/css/swiper.min.css" />
    @await RenderSectionAsync("Styles", required: false)
    <style>
        /* 隐藏google翻译的弹窗 */
        #goog-gt-tt {
            transform: scale(0, 0);
            background-color: transparent !important;
            -webkit-box-shadow: 0 0px 0px rgba(0,0,0,0) !important;
            -moz-box-shadow: 0 0px 0px rgba(0,0,0,0) !important;
            box-shadow: 0 0px 0px rgba(0,0,0,0) !important;
        }
        /* 隐藏google顶部横条 */
        .goog-te-banner-frame {
            display: none;
        }
        .el-notification.right{
            top:100px!important
        }
    </style>
    <!--google翻译功能加载-->
    <script type="text/javascript">
        function googleTranslateElementInit() {
            let langname = navigator.language ? navigator.language.split('-')[0].toLowerCase() : 'en'; //动态获取用户的语种，可以动态赋值到pageLanguage
            console.log(langname);
            new google.translate.TranslateElement({
                pageLanguage: 'ja', //页面语种
                includedLanguages: 'zh-CN,ja,en',  //期望翻译的语种，如果不设置默认全部语种
                autoDisplay: false,
                gaTrack: true,
                layout: google.translate.TranslateElement.InlineLayout.SIMPLE
            }, 'google_translate_element');
        }
    </script>
    <script src="https://translate.google.co.jp/translate_a/element.js?cb=googleTranslateElementInit" type="text/javascript"></script>
    
</head>

<body id="app">


    @* 全局衔接导航条 *@
    <partial name="_Header" />

    @* 页面内容 *@
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    @* 底部栏 *@
    <partial name="_Footer" />

    @* 返回顶部 *@
    <partial name="_ToTop" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.cookie.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- vue3 -->
    <script src="~/lib/vue/dist/vue.global.prod.js" asp-append-version="true"></script>
    <!-- elemnt-plus -->
    <script src="~/lib/element-plus/dist/index.full.min.js" asp-append-version="true"></script>
    <script src="~/lib/element-plus/locale/lang/zh-cn.js" asp-append-version="true"></script>
    <!-- axios -->
    <script src="~/lib/axios/dist/axios.min.js" asp-append-version="true"></script>
    <!-- 自定义js -->
    <script src="~/js/common.js" asp-append-version="true"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/loading.js"></script>
    <script src="~/js/utils.js"></script>
    <script src="~/js/is.js"></script>
    <script src="~/js/http.js"></script>
    <!--谷歌翻译清空-->
    <script>
        $(document).ready(function () {
            $.cookie("googtrans", "", { expires: -1 });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

THD/Views/Shared/_LeftBar.cshtml
@{
    string type = string.Empty;
    if (User.Identity.IsAuthenticated)
        type = User.Claims?.FirstOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.Role).Value;
}

<button type="button" class="btn btn-default" id="toggle-sidebar">
    <span class="glyphicon glyphicon-th-list"></span>
</button>
<div class="left-bar-bg">
</div>
<div class="left-bar-list">
    <div class="logo"><a href="/">春夏秋冬</a></div>
    <div class="addr">日本</div>
    <ul>
        <li>
            <a href="/Account/Login">会员登陆</a>
        </li>
        <li>
            <a href="/Account/Register">会员注册</a>
        </li>
        <li>
            <a href="">商家入驻</a>
        </li>
        <li>
            <a href="/MyRoom/Index">我的空间</a>
        </li>
        @if (User.Identity.IsAuthenticated && type is not null && (type.ToLower() == "admin" || type.ToLower() == "super")) {
            <li>
                <a href="/System/Index">后台管理</a>
            </li>
        }
        <li>
            <span onclick="logout()">退出登陆</span>
        </li>
    </ul>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    $(function () {
        $('#toggle-sidebar').click(function () {
            $('.left-bar-bg').css({
                'transform': 'translateX(0)',
                'background': 'rgba(0,0,0,.5)'
            })
            $('.left-bar-list').css({
                'transform': 'translateX(0)',
                'box-shadow': '5px 5px 10px #000'
            })
        });
        $('.left-bar-bg').click(function () {
            $('.left-bar-bg').css({
                'transform': 'translateX(-100%)',
                'background': 'rgba(0,0,0,0)'
            })
            $('.left-bar-list').css({
                'transform': 'translateX(-100%)',
                'box-shadow': '0 0'
            })
        });
    })
    function logout() {
        $.post("/Account/Logout", function (data, status) {
            window.location.href = "/";
        });
    }
</script>

THD/Views/Shared/_RightBar.cshtml
<div id="divTarget" class="h-full fixed top-0 right-0 w-10 text-white z-50" style="background: #3c3c3c">
    <div class="flex flex-col items-center s-items-center">
        <a href="/cart" class="right-menu r1" onmouseover="enter(0)">
            <span class="glyphicon glyphicon-shopping-cart " style="font-size: 20px; color: #ffffff">
                <br>
                <span id="ctl00_lbShoppingCartNum " style="color:White;font-size:9pt;"></span>
            </span>
            <div class="other">
                购物车
            </div>

        </a>
        <a href="#" class="right-menu r2">
            <span class="glyphicon glyphicon-signal " style="font-size: 20px; color: #ffffff">
                <br>
                <span id="ctl00_Label2" style="color:White;font-size:9pt;"></span>
            </span>
            <div class="other">
                您的积分
            </div>
        </a>
        <a href="#" class="right-menu r3">
            <span class="glyphicon glyphicon-qrcode " style="font-size: 20px; color: #ffffff"></span>
            <div class="other">
                二维码
            </div>
        </a>
    </div>
</div>
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script>
    const urlList = [
        'http://localhost:5000/',
        'http://www.cxqd-japan.com/',
        'http://localhost:5000/Account/Register',
        'http://www.cxqd-japan.com/Account/Register',
        'http://localhost:5000/Account/Login',
        'http://www.cxqd-japan.com/Account/Login',
    ]
    if (urlList.includes(window.location.href)) {
        $('#divTarget').css('display', 'none')
    } else {
        $('#divTarget').css('display', 'block')
    }
</script>

THD/Views/Shared/_SystemLeftBar.cshtml
@{
    var controllerName = Context.Request.RouteValues["Controller"]?.ToString();
}

@* 后台管理 *@

@* 左边界 *@
<div class="homeMyRoomLeftArea">
    @if (controllerName.Equals("system", StringComparison.OrdinalIgnoreCase))
    {
        <ul>
            <li style="background-color: #666666; color: #ffffff; width: 100%; line-height: 25px; vertical-align: middle; text-align: center; font-size: 15px;">案件管理</li>
            <li>
                <a id="LinkButton1" asp-area="" asp-controller="System" asp-action="AddItListInfo" asp-route-Id="">案件掲載</a>
            </li>
            <li>
                <a id="LinkButton4" asp-area="" asp-controller="System" asp-action="ItListInfoList">案件一覧</a>
            </li>
            <li>
            <li style="background-color: #666666; color: #ffffff; width: 100%; line-height: 25px; vertical-align: middle; text-align: center; font-size: 15px;">エンジニア管理</li>
            <li>
                <a id="LinkButton9" asp-area="" asp-controller="System" asp-action="TourList">履歴記載</a>
            </li>
            <li>
                <a id="LinkButton10" asp-area="" asp-controller="System" asp-action="StayList">履歴一覧</a>
            </li>
            @if (User.IsInRole("admin"))
            {
                <li style="background-color: #666666; color: #ffffff; width: 100%; line-height: 25px; vertical-align: middle; text-align: center; font-size: 15px;">管理者</li>
                <li>
                    <a id="LinkButton27" asp-area="" asp-controller="System" asp-action="Member">通販会員</a>
                </li>
                <li>
                    <a id="LinkButton27" asp-area="" asp-controller="System" asp-action="Technician">登峰会員</a>
                </li>
                <li>
                    <a id="LinkButton28" asp-area="" asp-controller="System" asp-action="CorporateList">お問合せ管理</a>
                </li>
            }
        </ul>
    }
    else if (controllerName.Equals("admin", StringComparison.OrdinalIgnoreCase))
    {
        <ul>
            <li style="background-color: #666666; color: #ffffff; width: 100%; line-height: 25px; vertical-align: middle; text-align: center; font-size: 15px;">社内管理</li>
            <li>
                <a id="ctl00_body_LinkButton1" asp-area="" asp-controller="MyRoom" asp-action="MemberInfo">会員管理</a>
            </li>
            <li>
                <a id="ctl00_body_LinkButton2" asp-area="" asp-controller="MyRoom" asp-action="Photo">お問合わせ管理</a>
            </li>
            <li>
                <a id="ctl00_body_LinkButton3" asp-area="" asp-controller="MyRoom" asp-action="PasswordChange">掲載管理</a>
            </li>
            <li>
                <a id="ctl00_body_LinkButton4" asp-area="" asp-controller="MyRoom" asp-action="Quitters">実績管理</a>
            </li>
        </ul>
    }
</div>

THD/Views/Shared/_ToTop.cshtml
<div class="to-top">
    <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
</div>